
version: '3.7'

services:

  postgres:
    image: postgres:14-alpine
    ports:
      - '3306:3306'
    volumes:
      - .data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB=db
      POSTGRES_USER=student
      POSTGRES_PASSWORD=KGPRKS

